### PR TITLE
Added ETA Functionality

### PR DESCRIPTION
**Pull request by DeadMan30**
This change adds the eta functionality to the mega file downloads.

Screenshot_2024-03-06-17-21-47-84_0b342c26d6c44f3c8d2de40eabb4e1da

### CODE REVIEW

**Comment by XronTrix10** [comment]
Hi @DeadMan30 That's an awesome fix. Thank you for the commit. Just one thing to change, There is already a format time function, most probably located in utils. Please use that and remove the new function. No need to work extra 🙌

After it We are good to go

**Comment by XronTrix10** [comment]
I created an issue for it, next time you make a commit, mention that issue here :)

**Comment by DeadMan30** [comment]
Done.

**Comment by XronTrix10** [comment]
Nice. Approved ! @DeadMan30

**Pull request merged**
