### PR TITLE
Improve download speed by manipulating Aria2 command line flags

### PR DESCRIPTION
**Pull request by hstsethi**
I [myself](https://github.com/hstsethi/no-frills-dotfiles/blob/main/aria2/aria2.conf) use these flags. This makes it pretty fast.

### CODE REVIEW

**Comment by vippawar1104** [comment]
# Configuration settings for the download manager
max-concurrent-downloads=50000
max-connections-per-server=20
user-agent="Mozilla/5.0 (Linux; Android 11; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Mobile Safari/537.36"
log-level=info
min-split-size=2M
max-total-download-limit=0
this also make it pretty fast

**Comment by vippawar1104** [comment]
can u pls review it @XronTrix10

**Comment by hstsethi** [comment]
> # Configuration settings for the download manager
> max-concurrent-downloads=50000 max-connections-per-server=20 user-agent="Mozilla/5.0 (Linux; Android 11; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Mobile Safari/537.36" log-level=info min-split-size=2M max-total-download-limit=0 this also make it pretty fast



Why make split size from 1M to 2M?

AFAIK aria2c only supports max 16 connections per server.

**Comment by hstsethi** [comment]
> # Configuration settings for the download manager
> max-concurrent-downloads=50000 max-connections-per-server=20 user-agent="Mozilla/5.0 (Linux; Android 11; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Mobile Safari/537.36" log-level=info min-split-size=2M max-total-download-limit=0 this also make it pretty fast



Why make split size from 1M to 2M?

AFAIK aria2 only supports max 16 connections per server.

Edit: [source](https://github.com/aria2/aria2/issues/580)

**Comment by vippawar1104** [comment]
Changing the split size from 1M to 2M in aria2 can help optimize download performance by reducing the overhead associated with managing smaller chunks. With larger split sizes, there are fewer pieces to handle, which can lead to improved efficiency, especially when downloading large files.

Since aria2 allows a maximum of 16 connections per server, increasing the split size might help in utilizing those connections more effectively, allowing for better bandwidth management and potentially faster download speeds.

Also, consider the balance between split size and your internet connection. If your connection can handle larger chunks without issues, this change can help you get the most out of your downloads. However, if you're working with a slower or more unstable connection, you might want to test smaller split sizes to see what works best for your setup.

**Comment by hstsethi** [comment]
> Changing the split size from 1M to 2M in aria2 can help optimize download performance by reducing the overhead associated with managing smaller chunks. With larger split sizes, there are fewer pieces to handle, which can lead to improved efficiency, especially when downloading large files.
> 
> Since aria2 allows a maximum of 16 connections per server, increasing the split size might help in utilizing those connections more effectively, allowing for better bandwidth management and potentially faster download speeds.
> 
> Also, consider the balance between split size and your internet connection. If your connection can handle larger chunks without issues, this change can help you get the most out of your downloads. However, if you're working with a slower or more unstable connection, you might want to test smaller split sizes to see what works best for your setup.

Interesting. Would love to see actual benchmarks. 

BTW [here](https://github.com/aria2/aria2/issues/580) is source on Aria2 max connection limit.

**Comment by vippawar1104** [comment]
Benchmarks can vary based on several factors, including the specific server, network conditions, and the type of files being downloaded. However, you might find some general trends in benchmarks comparing different split sizes in tools like aria2:
Performance with Larger Splits: Tests often show that increasing the split size (from 1M to 2M) can lead to improved download speeds due to reduced connection management overhead and better utilization of available bandwidth.
Optimal Split Size: Some benchmarks suggest an optimal split size for specific situations. For instance, huge files might perform better with larger splits, while smaller files might benefit from smaller splits.
Network Conditions: Larger splits often yield better results in stable, high-bandwidth environments. However, in unstable conditions (like Wi-Fi), smaller splits might help resume downloads more effectively after interruptions.
Real-World Tests: Users often share their benchmarks in forums or on GitHub. Searching for specific tests comparing different configurations can provide insights into what you might expect in your setup.
If you’re considering running your benchmarks, try testing with various split sizes while keeping other settings constant. Monitor the download speeds, success rates, and resource usage to find the best configuration for your needs!

**Comment by hstsethi** [comment]
> Benchmarks can vary based on several factors, including the specific server, network conditions, and the type of files being downloaded. However, you might find some general trends in benchmarks comparing different split sizes in tools like aria2: Performance with Larger Splits: Tests often show that increasing the split size (from 1M to 2M) can lead to improved download speeds due to reduced connection management overhead and better utilization of available bandwidth. Optimal Split Size: Some benchmarks suggest an optimal split size for specific situations. For instance, huge files might perform better with larger splits, while smaller files might benefit from smaller splits. Network Conditions: Larger splits often yield better results in stable, high-bandwidth environments. However, in unstable conditions (like Wi-Fi), smaller splits might help resume downloads more effectively after interruptions. Real-World Tests: Users often share their benchmarks in forums or on GitHub. Searching for specific tests comparing different configurations can provide insights into what you might expect in your setup. If you’re considering running your benchmarks, try testing with various split sizes while keeping other settings constant. Monitor the download speeds, success rates, and resource usage to find the best configuration for your needs!

ChatGPT generated response isn't empirical evidence. The issues it talks about can be easily solved by a large enough sample size.

**Comment by vippawar1104** [comment]
how can  u say that it is generated by ChatGPT

**Comment by vippawar1104** [comment]
its an allegation  brother

**Pull request merged**
