### PR TITLE
Added MegaDL 

### PR DESCRIPTION
**Pull request by thehellruler**
Added MegaDL #6

### CODE REVIEW

**Comment by XronTrix10** [comment]
Awesome !! Can you provide some screenshots for the working mega download ?. Also extract the Download name from mega link in getdownloadname method

**Comment by XronTrix10** [comment]
That's awesome, Thanks for the changes. Just one thing is left, that is to get the download name before it starts downloading.

Refer to [This Line](https://github.com/XronTrix10/Telegram-Leecher/blob/f68251f197ac21c21c934c8ba70a46c2d245bfa9/colab_leecher/downlader/manager.py#L129) , Please try to get the download name which is missing here. It will be very helpful

**Comment by thehellruler** [comment]
Getting file name before download isn't possible, but it will be updated as soon as the download starts.
[here](https://github.com/thehellruler/Telegram-Leecher/blob/e1ce519383e3a25be722e8ba5736c7029047bbad/colab_leecher/downlader/mega.py#L39)

**Comment by XronTrix10** [comment]
I couldn't verify it by myself, but I hope you did and it's working. Pull request approved ! But in case of any future megadl issue, you will be mentioned

**Comment by thehellruler** [comment]
Yeah , sure.

**Pull request merged**
